import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const screenStyles = StyleSheet.create({
  authBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    backgroundColor: '#1a1a1a',
  },
  authBackgroundStyle: {
    opacity: 0.9,
    transform: [{ translateY: -120 }],
  },
  authGradient: {
    flex: 1,
  },
  authContainer: {
    flex: 1,
  },
  authScrollContent: {
    flexGrow: 1,
    paddingTop: 80,
  },
  authHeader: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  authTitle: {
    fontSize: 36,
    fontWeight: '700',
    color: colors.text.white,
    marginBottom: 16,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 0.5,
  },
  authDescription: {
    fontSize: 18,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 26,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    fontWeight: '500',
    maxWidth: 280,
  },
  authFormContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  authCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  authInputContainer: {
    marginBottom: 12,
  },
  authButton: {
    marginTop: 8,
    marginBottom: 16,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  authSecondaryButton: {
    borderRadius: 12,
    paddingVertical: 14,
  },
  
  
  addBenchHeaderCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  addBenchSectionCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  addBenchSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary[600],
    marginBottom: 16,
  },
  addBenchInputContainer: {
    marginBottom: 0,
  },
  addBenchTextInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  addBenchGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  addBenchOption: {
    width: '48%',
    backgroundColor: colors.background.secondary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: colors.gray[300],
    position: 'relative',
  },
  addBenchOptionSelected: {
    borderColor: colors.primary[600],
    backgroundColor: colors.gradient.light,
  },
  addBenchIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  addBenchName: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text.primary,
    textAlign: 'center',
  },
  addBenchCheckmark: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  addBenchInfoCard: {
    backgroundColor: 'rgba(46, 125, 50, 0.1)',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(46, 125, 50, 0.2)',
  },
  addBenchInfoIconContainer: {
    marginRight: 12,
  },
  addBenchLocationInfo: {
    flex: 1,
  },
  addBenchInfoText: {
    fontSize: 14,
    color: colors.primary[600],
    fontWeight: '600',
    marginBottom: 2,
  },
  addBenchInfoSubtext: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  addBenchSaveButton: {
    backgroundColor: colors.primary[600],
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  
  benchDetailsContainer: {
    flex: 1,
    backgroundColor: colors.gradient.lighter,
  },
  benchDetailsScrollContent: {
    paddingBottom: 30,
  },
  benchDetailsLoading: {
    textAlign: 'center',
    marginTop: 50,
    fontSize: 16,
    color: '#6b7280',
  },
  benchDetailsBenchInfo: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  benchDetailsIcon: {
    fontSize: 60,
    marginRight: 16,
    backgroundColor: colors.gradient.lighter,
    padding: 12,
    borderRadius: 50,
    textAlign: 'center',
    width: 80,
    height: 80,
    lineHeight: 56,
  },
  benchDetailsBenchDetails: {
    flex: 1,
  },
  benchDetailsBenchName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 8,
  },
  benchDetailsDescription: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 12,
    lineHeight: 22,
  },
  benchDetailsRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  benchDetailsRatingText: {
    fontSize: 16,
    color: '#6b7280',
    marginLeft: 8,
  },
  benchDetailsLocation: {
    fontSize: 14,
    color: '#9ca3af',
    marginBottom: 4,
  },
  benchDetailsAddedBy: {
    fontSize: 14,
    color: '#9ca3af',
  },
  benchDetailsSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  benchDetailsSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 16,
  },
  benchDetailsRatingForm: {
    marginTop: 16,
  },
  benchDetailsStarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  benchDetailsCommentInput: {
    marginBottom: 16,
  },
  benchDetailsSubmitButton: {
    marginTop: 8,
  },
  benchDetailsNoRatings: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  benchDetailsRatingItem: {
    backgroundColor: '#f9fafb',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  benchDetailsRatingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  benchDetailsRatingUser: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
  },
  benchDetailsRatingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  benchDetailsRatingDate: {
    fontSize: 14,
    color: '#6b7280',
    marginLeft: 8,
  },
  benchDetailsRatingComment: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
  },
  
  // MapScreen styles
  mapScreenContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  mapScreenControlButtonsContainer: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 1000,
    flexDirection: 'column',
    gap: 12,
  },
  mapScreenControlButton: {
    backgroundColor: 'rgba(124, 179, 66, 0.65)',
    borderRadius: 30,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    borderWidth: 1,
    borderColor: 'rgba(124, 179, 66, 0.65)',
  },
  
  // BenchListScreen styles
  benchListContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  benchListSearchContainer: {
    padding: 16,
    paddingBottom: 12,
  },
  benchListSearchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(46, 125, 50, 0.1)',
  },
  benchListSearchIcon: {
    marginRight: 12,
    color: colors.primary[600],
  },
  benchListSearchInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text.primary,
    paddingVertical: 2,
    fontWeight: '500',
  },
  benchListSearchClearButton: {
    padding: 6,
    backgroundColor: colors.gray[200],
    borderRadius: 12,
    marginLeft: 8,
  },
  benchListListContent: {
    padding: 16,
  },
  benchListBenchCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  benchListBenchIconContainer: {
    width: 50,
    height: 50,
    backgroundColor: colors.gradient.light,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  benchListBenchIcon: {
    fontSize: 24,
  },
  benchListBenchContent: {
    flex: 1,
  },
  benchListBenchDescription: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  benchListBenchMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  benchListRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  benchListRatingText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 4,
  },
  benchListUsernameText: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
  },
  benchListLocationText: {
    fontSize: 12,
    color: '#999',
  },
  benchListEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  benchListEmptyGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  benchListEmptyIconContainer: {
    marginBottom: 20,
  },
  benchListEmptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  benchListEmptyText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  benchListEmptyButton: {
    backgroundColor: colors.primary[600],
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  benchListEmptyContentContainer: {
    flex: 1,
  },
  
  // ProfileScreen styles
  profileContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  profileHeader: {
    paddingTop: 20,
    paddingBottom: 32,
    alignItems: 'center',
  },
  profileProfileSection: {
    alignItems: 'center',
  },
  profileAvatarContainer: {
    marginBottom: 12,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileUserName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  profileUserEmail: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  profileStatsCard: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: -16,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  profileStatItem: {
    alignItems: 'center',
  },
  profileStatNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#22c55e',
    marginBottom: 4,
  },
  profileStatLabel: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
  },
  profileStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#e5e7eb',
  },
  profileMenuCard: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  profileMenuItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileMenuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  profileMenuItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  profileMenuIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gradient.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  profileMenuTextContainer: {
    flex: 1,
  },
  profileMenuTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 2,
  },
  profileMenuSubtitle: {
    fontSize: 14,
    color: '#6b7280',
  },
  profileLogoutContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 32,
  },
});
