import { StyleSheet } from 'react-native';
import { colors, shadows } from './colors';

export const screenStyles = StyleSheet.create({
  authBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    backgroundColor: '#1a1a1a',
  },
  authBackgroundStyle: {
    opacity: 0.9,
    transform: [{ translateY: -120 }],
  },
  authGradient: {
    flex: 1,
  },
  authContainer: {
    flex: 1,
  },
  authScrollContent: {
    flexGrow: 1,
    paddingTop: 80,
  },
  authHeader: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  authTitle: {
    fontSize: 36,
    fontWeight: '700' as '700',
    color: colors.text.white,
    marginBottom: 16,
    textAlign: 'center' as 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 0.5,
  },
  authDescription: {
    fontSize: 18,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center' as 'center',
    lineHeight: 26,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    fontWeight: '500' as '500',
    maxWidth: 280,
  },
  authFormContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  authCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 20,
    padding: 24,
    ...shadows.button,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  authInputContainer: {
    marginBottom: 12,
  },
  authUsernameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  authUsernameInput: {
    flex: 1,
    marginBottom: 0,
  },
  authRandomNicknameButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.primary[100],
    justifyContent: 'center',
  },
  authRandomNicknameButtonText: {
    color: colors.primary[700],
    fontWeight: '600',
    fontSize: 14,
  },
  authButton: {
    marginTop: 8,
    marginBottom: 16,
    paddingVertical: 14,
    borderRadius: 12,
    ...shadows.medium,
  },
  authSecondaryButton: {
    borderRadius: 12,
    paddingVertical: 14,
  },
  
  
  addBenchHeaderCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    ...shadows.medium,
  },
  addBenchSectionCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    ...shadows.medium,
  },
  addBenchSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold' as 'bold',
    color: colors.primary[600],
    marginBottom: 16,
  },
  addBenchInputContainer: {
    marginBottom: 0,
  },
  addBenchLocationOptions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  addBenchLocationOption: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.gray[300],
  },
  addBenchLocationOptionIcon: {
    marginBottom: 8,
  },
  addBenchLocationOptionTitle: {
    fontSize: 15,
    fontWeight: '600' as '600',
    color: colors.text.primary,
    marginBottom: 4,
  },
  addBenchTextInput: {
    minHeight: 80,
    textAlignVertical: 'top' as 'top',
  },
  addBenchGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  addBenchOption: {
    width: '48%',
    backgroundColor: colors.background.secondary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: colors.gray[300],
    position: 'relative',
  },
  addBenchOptionSelected: {
    borderColor: colors.primary[600],
    backgroundColor: colors.gradient.light,
  },
  addBenchIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  addBenchName: {
    fontSize: 12,
    fontWeight: '600' as '600',
    color: colors.text.primary,
    textAlign: 'center' as 'center',
  },
  addBenchCheckmark: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  addBenchInfoCard: {
    backgroundColor: 'rgba(46, 125, 50, 0.1)',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(46, 125, 50, 0.2)',
  },
  addBenchInfoIconContainer: {
    marginRight: 12,
  },
  addBenchLocationInfo: {
    flex: 1,
  },
  addBenchInfoText: {
    fontSize: 14,
    color: colors.primary[600],
    fontWeight: '600' as '600',
    marginBottom: 2,
  },
  addBenchInfoSubtext: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  addBenchSaveButton: {
    backgroundColor: colors.primary[600],
    paddingVertical: 16,
    borderRadius: 12,
    ...shadows.button,
  },
  
  benchDetailsContainer: {
    flex: 1,
    backgroundColor: colors.gradient.lighter,
  },
  benchDetailsScrollContent: {
    paddingBottom: 30,
  },
  benchDetailsLoading: {
    textAlign: 'center' as 'center',
    marginTop: 50,
    fontSize: 16,
    color: colors.text.secondary,
  },
  benchDetailsBenchInfo: {
    backgroundColor: colors.background.primary,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    ...shadows.medium,
  },
  benchDetailsIcon: {
    fontSize: 60,
    marginRight: 16,
    backgroundColor: colors.gradient.lighter,
    padding: 12,
    borderRadius: 50,
    textAlign: 'center' as 'center',
    width: 80,
    height: 80,
    lineHeight: 56,
  },
  benchDetailsBenchDetails: {
    flex: 1,
  },
  benchDetailsBenchName: {
    fontSize: 22,
    fontWeight: 'bold' as 'bold',
    color: colors.text.primary,
    marginBottom: 8,
  },
  benchDetailsDescription: {
    fontSize: 16,
    color: colors.text.secondary,
    marginBottom: 12,
    lineHeight: 22,
  },
  benchDetailsRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  benchDetailsRatingText: {
    fontSize: 16,
    color: colors.text.secondary,
    marginLeft: 8,
  },
  benchDetailsLocation: {
    fontSize: 14,
    color: colors.text.disabled,
    marginBottom: 4,
  },
  benchDetailsAddedBy: {
    fontSize: 14,
    color: colors.text.disabled,
  },
  benchDetailsSection: {
    backgroundColor: colors.background.primary,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    ...shadows.medium,
  },
  benchDetailsSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold' as 'bold',
    color: colors.text.primary,
    marginBottom: 16,
  },
  benchDetailsRatingForm: {
    marginTop: 16,
  },
  benchDetailsStarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  benchDetailsCommentInput: {
    marginBottom: 16,
  },
  benchDetailsSubmitButton: {
    marginTop: 8,
  },
  benchDetailsNoRatings: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center' as 'center',
    fontStyle: 'italic' as 'italic',
  },
  benchDetailsRatingItem: {
    backgroundColor: colors.gray[50],
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  benchDetailsRatingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  benchDetailsRatingUser: {
    fontSize: 16,
    fontWeight: '600' as '600',
    color: colors.text.primary,
  },
  benchDetailsRatingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  benchDetailsRatingDate: {
    fontSize: 14,
    color: colors.text.secondary,
    marginLeft: 8,
  },
  benchDetailsRatingComment: {
    fontSize: 14,
    color: colors.text.primary,
    lineHeight: 20,
  },

  mapScreenContainer: {
    flex: 1,
    backgroundColor: colors.gray[100],
  },
  mapScreenControlButtonsContainer: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 1000,
    flexDirection: 'column',
    gap: 12,
  },
  mapScreenControlButton: {
    backgroundColor: 'rgba(124, 179, 66, 0.65)',
    borderRadius: 30,
    padding: 12,
    ...shadows.button,
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    borderWidth: 1,
    borderColor: 'rgba(124, 179, 66, 0.65)',
  },

  benchListContainer: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  benchListSearchContainer: {
    padding: 16,
    paddingBottom: 12,
  },
  benchListSearchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...shadows.large,
    borderWidth: 1,
    borderColor: 'rgba(46, 125, 50, 0.1)',
  },
  benchListSearchIcon: {
    marginRight: 12,
    color: colors.primary[600],
  },
  benchListSearchInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text.primary,
    paddingVertical: 2,
    fontWeight: '500',
  },
  benchListSearchClearButton: {
    padding: 6,
    backgroundColor: colors.gray[200],
    borderRadius: 12,
    marginLeft: 8,
  },
  benchListListContent: {
    padding: 16,
  },
  benchListBenchCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    ...shadows.medium,
  },
  benchListBenchIconContainer: {
    width: 50,
    height: 50,
    backgroundColor: colors.gradient.light,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    ...shadows.small,
  },
  benchListBenchIcon: {
    fontSize: 24,
  },
  benchListBenchContent: {
    flex: 1,
  },
  benchListBenchDescription: {
    fontSize: 16,
    fontWeight: '600' as '600',
    color: colors.text.primary,
    marginBottom: 8,
  },
  benchListBenchMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  benchListRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  benchListRatingText: {
    fontSize: 14,
    color: colors.text.secondary,
    marginLeft: 4,
  },
  benchListUsernameText: {
    fontSize: 12,
    color: colors.text.disabled,
    fontStyle: 'italic' as 'italic',
  },
  benchListLocationText: {
    fontSize: 12,
    color: colors.text.disabled,
  },
  benchListEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  benchListEmptyGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  benchListEmptyIconContainer: {
    marginBottom: 20,
  },
  benchListEmptyTitle: {
    fontSize: 24,
    fontWeight: 'bold' as 'bold',
    color: colors.text.primary,
    marginBottom: 12,
    textAlign: 'center' as 'center',
  },
  benchListEmptyText: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center' as 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  benchListEmptyButton: {
    backgroundColor: colors.primary[600],
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  benchListEmptyContentContainer: {
    flex: 1,
  },

  profileContainer: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  profileHeader: {
    paddingTop: 20,
    paddingBottom: 32,
    alignItems: 'center',
  },
  profileProfileSection: {
    alignItems: 'center',
  },
  profileAvatarContainer: {
    marginBottom: 12,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileUserName: {
    fontSize: 24,
    fontWeight: 'bold' as 'bold',
    color: colors.text.white,
    marginBottom: 4,
  },
  profileUserEmail: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  profileStatsCard: {
    backgroundColor: colors.background.primary,
    marginHorizontal: 16,
    marginTop: -16,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    ...shadows.medium,
  },
  profileStatItem: {
    alignItems: 'center',
  },
  profileStatNumber: {
    fontSize: 24,
    fontWeight: 'bold' as 'bold',
    color: colors.success,
    marginBottom: 4,
  },
  profileStatLabel: {
    fontSize: 14,
    color: colors.text.secondary,
    textAlign: 'center' as 'center',
  },
  profileStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.gray[200],
  },
  profileMenuCard: {
    backgroundColor: colors.background.primary,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    ...shadows.medium,
  },
  profileMenuItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileMenuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  profileMenuItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  profileMenuIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gradient.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  profileMenuTextContainer: {
    flex: 1,
  },
  profileMenuTitle: {
    fontSize: 16,
    fontWeight: '600' as '600',
    color: colors.text.primary,
    marginBottom: 2,
  },
  profileMenuSubtitle: {
    fontSize: 14,
    color: colors.text.secondary,
  },
  profileLogoutContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 32,
  },
  benchDetailsRarityContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  benchDetailsRarityButton: {
    flex: 1,
    minWidth: '45%',
    marginHorizontal: 5,
  },
  benchDetailsRarityButtonSelected: {
    backgroundColor: colors.primary[500],
    borderColor: colors.primary[600],
  },
});
